### ISSUE TITLE
.classpath

### ISSUE THREAD

**Issue by LinusDierheimer** [iamrohitsuthar/LiveChatServer#11]
The github-tags say that it should be at least java 8, but .classpath loads the project with java 1.7 in eclipse. I highly recommend switching to a higher java version, at least 8 for lambda expressions functional interfaces and java.nio (replace old java.io.File class). I even would suggest to use the latest version, java 13. This would increase security and speed and usable language features.  
The second point is, that a library you are using is configured as an external jar, which is located in your download folder (`/home/iamrohitsuthar/Downloads/mysql-connector-java-5.1.47/mysql-connector-java-5.1.47.jar`). Nobody of us has this username, so we are forced to edit .classpath, wich leads to unnecessary work with git. I recommend putting the jar a repository folder like `third-party` and use a relative link to it. It is licensed under GPL v2, so this shouldn't be a problem, as long as the project stays open-source. This would also be a benefit to all contributers, because nowhere is documented which version is needed or at least that this library is necessary at all.  
As a tipp, it is considered as good practice not to commit and push any IDE specific files at all, so every developer can stuck to his choice of favor.  
  
Regards,
Linus

**Comment by LinusDierheimer** [comment]
By the way, the version of the mysql connector is very outdated, to support latest mysql releases, switch to the 8.x branch.

**Comment by iamrohitsuthar** [comment]
@LinusDierheimer 
Please review the changes.

**Comment by LinusDierheimer** [comment]
Looks good :+1:
